inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - 'test/dummy/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'wicked_pdf.gemspec'

Metrics/ClassLength:
  Exclude:
    - 'lib/wicked_pdf.rb'

# I'd like wicked_pdf to keep Ruby 1.8 compatibility for now
Style/HashSyntax:
  EnforcedStyle: hash_rockets
